### ISSUE TITLE
当末影龙死亡时，插件似乎在BC输出了什么内容使geyser的BE玩家断开连接

### ISSUE THREAD

**Issue by CNDogc** [iXanadu13/EnderDragon#13]
[19:00:34 WARN]: [/127.0.0.1:0|BE_FizzyKitty018] <-> DownstreamBridge <-> [lobby] - could not decode packet!
io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: ["§7[§e系统§7]§r ","末影龙奖励已发放！"]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: ["§7[§e系统§7]§r ","末影龙奖励已发放！"]
        at com.google.gson.Gson.fromJson(Gson.java:1238) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:140) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:171) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:118) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:117) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.packet.SystemChat.read(SystemChat.java:27) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:517) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        ... 20 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: ["§7[§e系统§7]§r ","末影龙奖励已发放！"]
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:154) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:140) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:171) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:29) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:118) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:117) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.packet.SystemChat.read(SystemChat.java:27) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:517) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        ... 20 more
[19:00:34 INFO]: [yantuA] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[19:00:34 INFO]: [BE_chen1548] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[19:00:34 INFO]: [BE_FizzyKitty018] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[19:00:34 INFO] [floodgate]: Floodgate 玩家 BE_chen1548 已断开连接
[19:00:34 INFO] [floodgate]: Floodgate 玩家 BE_FizzyKitty018 已断开连接
[19:00:34 INFO] [Geyser-BungeeCord]: chen1548 因为 The server you were previously on went down, you have been connected to a fallback server 与 Java 版服务器 断开了连接
[19:00:34 INFO] [Geyser-BungeeCord]: FizzyKitty01861 因为 The server you were previously on went down, you have been connected to a fallback server 与 Java 版服务器 断开了连接

**Comment by iXanadu13** [comment]
加下qq群：309699577

**Comment by iXanadu13** [comment]
请提供对解决问题有帮助的以下信息：服务端类型及版本，插件版本，末影龙配置等等内容。
此外，插件没有暂时对BC服作特殊处理，但只要子服务器为Bukkit系列服务端基本不存在兼容问题。但在一些特殊的环境下的兼容性未知，比如使用面板开服、使用Geyser或其他方式进行基岩版互通的等等。
