### ISSUE TITLE
can't seems to spawn the dragon using /ed spawn or /ed respawn

### ISSUE THREAD

**Issue by AdwinL** [iXanadu13/EnderDragon#21]
[17May2024 18:37:13.098] [Server thread/ERROR] [Minecraft/]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ed' in plugin EnderDragon v2.5.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.20.4-1.0.3-13f0d63.jar!/:arclight-1.20.4-1.0.3-13f0d63] {re:classloading,re:mixin}
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.20.4-1.0.3-13f0d63.jar!/:arclight-1.20.4-1.0.3-13f0d63] {re:mixin,re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServerMixin.java:887) ~[arclight-1.20.4-1.0.3-13f0d63.jar!/:arclight-1.20.4-1.0.3-13f0d63] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:bukkit.CraftServerMixin_Forge,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin}
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[arclight-1.20.4-1.0.3-13f0d63.jar!/:arclight-1.20.4-1.0.3-13f0d63] {re:classloading}
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar!/:?] {re:computing_frames}
	at net.minecraft.commands.execution.tasks.ExecuteCommand.m_304778_(ExecuteCommand.java:29) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:classloading}
	at net.minecraft.commands.execution.tasks.ExecuteCommand.m_304778_(ExecuteCommand.java:13) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:classloading}
	at net.minecraft.commands.execution.UnboundEntryAction.m_306587_(UnboundEntryAction.java:8) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:classloading}
	at net.minecraft.commands.execution.CommandQueueEntry.m_305080_(CommandQueueEntry.java:8) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:classloading}
	at net.minecraft.commands.execution.ExecutionContext.m_304919_(ExecutionContext.java:107) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:classloading}
	at net.minecraft.commands.Commands.m_306801_(CommandsMixin_Forge.java:351) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:commands.CommandsMixin,pl:mixin:APP:mixins.arclight.forge.json:core.command.CommandsMixin_Forge,pl:mixin:A}
	at net.minecraft.commands.Commands.m_242674_(CommandsMixin_Forge.java:280) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:commands.CommandsMixin,pl:mixin:APP:mixins.arclight.forge.json:core.command.CommandsMixin_Forge,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerPlayNetHandlerMixin_Forge.java:2729) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.network.ServerPlayNetHandlerMixin_Forge,pl:mixin:APP:mixins.arclight.impl.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerPlayNetHandlerMixin_Forge.java:1188) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.network.ServerPlayNetHandlerMixin_Forge,pl:mixin:APP:mixins.arclight.impl.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin_Forge.java:788) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin_Forge.java:162) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin_Forge.java:771) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin_Forge.java:765) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin_Forge.java:751) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin_Forge.java:2165) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin_Forge.java:256) ~[forge-1.20.4-49.0.31-server.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.arclight.forge.json:core.server.MinecraftServerMixin_Forge,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin,re:mixin,re:mixin}
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.world.level.dimension.end.EndDragonFight.tryRespawn()'
	at org.bukkit.craftbukkit.v1_20_R3.boss.CraftDragonBattle.initiateRespawn(CraftDragonBattle.java:72) ~[arclight-1.20.4-1.0.3-13f0d63.jar!/:arclight-1.20.4-1.0.3-13f0d63] {re:classloading}
	at pers.xanadu.enderdragon.manager.DragonManager.initiateRespawn(DragonManager.java:399) ~[?:?] {}
	at pers.xanadu.enderdragon.manager.DragonManager.initiateRespawn(DragonManager.java:367) ~[?:?] {}
	at pers.xanadu.enderdragon.command.MainCommand.onCommand(MainCommand.java:113) ~[?:?] {}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.20.4-1.0.3-13f0d63.jar!/:arclight-1.20.4-1.0.3-13f0d63] {re:classloading,re:mixin}
	... 28 more

**Comment by iXanadu13** [comment]
It's a bug about arclight-1.20.4-forge. This command works fine in spigot, paper servers.
I've feedback it to arclight: https://github.com/IzzelAliz/Arclight/issues/1352
Anyway, thanks for your feedback.
